spring.application.name=pedidos-service

# Base de datos en memoria H2 con compatibilidad MODE=LEGACY para soportar CALL IDENTITY()
spring.datasource.url=jdbc:h2:mem:pedidosdb;MODE=LEGACY;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Inicializacion de esquemas y datos
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Logs
logging.level.com.tienda.pedidos=DEBUG
